apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlclusters.mysql.operator.luktom.net
spec:
  group: mysql.operator.luktom.net
  names:
    kind: MysqlCluster
    listKind: MysqlClusterList
    plural: mysqlclusters
    singular: mysqlcluster
  scope: Cluster
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
