#!/usr/bin/env ansible-playbook
---
- name: Manage mysql database
  hosts: localhost
  gather_facts: no

  vars:
    state: present
    drop_on_delete: false

  tasks:
  - name: set status
    k8s_status:
      api_version: mysql.operator.luktom.net/v1
      kind: MysqlDatabase
      name: "{{ meta.name }}"
      namespace: "{{ meta.namespace }}"
      status:
        stage: "checking cluster"

  - include_tasks: ../common/credentials.yaml

  - when: state == "present"
    block:
    - name: set status
      k8s_status:
        api_version: mysql.operator.luktom.net/v1
        kind: MysqlDatabase
        name: "{{ meta.name }}"
        namespace: "{{ meta.namespace }}"
        status:
          stage: "creating"

    - name: create database
      mysql_db:
        login_host: "{{ cluster.spec.host }}"
        login_user: "{{ cluster.spec.username }}"
        login_password: "{{ cluster_secret.data.password | b64decode }}"
        name: "{{ meta.name }}"

    - name: set status
      k8s_status:
        api_version: mysql.operator.luktom.net/v1
        kind: MysqlDatabase
        name: "{{ meta.name }}"
        namespace: "{{ meta.namespace }}"
        status:
          created: true
          stage: "created"

  - when: state == "absent"
    block:
    - name: set status
      k8s_status:
        api_version: mysql.operator.luktom.net/v1
        kind: MysqlDatabase
        name: "{{ meta.name }}"
        namespace: "{{ meta.namespace }}"
        status:
          stage: "deleting"

    - name: delete database
      mysql_db:
        login_host: "{{ cluster.spec.host }}"
        login_user: "{{ cluster.spec.username }}"
        login_password: "{{ cluster_secret.data.password | b64decode }}"
        name: "{{ meta.name }}"
        state: absent
      when: drop_on_delete