apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-operator
  template:
    metadata:
      labels:
        name: mysql-operator
    spec:
      serviceAccountName: mysql-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "luktom/mysql-operator"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
          env:
          - name: ANSIBLE_VERBOSITY
            value: "4"
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 256Mi
        - name: operator
          image: "luktom/mysql-operator"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          args: [ "--verbose" ]
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mysql-operator"
            - name: ANSIBLE_VERBOSITY
              value: "4"
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 256Mi
      volumes:
        - name: runner
          emptyDir: {}
